SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

DROP TABLE IF EXISTS `USERS`;

CREATE TABLE IF NOT EXISTS `USERS` (
  name varchar(50) NOT NULL DEFAULT '',
  email varchar(125) NOT NULL DEFAULT '',
  tel varchar(10) NOT NULL DEFAULT '',
  password varchar(300) NOT NULL DEFAULT '',
  PRIMARY KEY (email)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

